version: '2'

services:

    web:
        build: .
        image: nginx-nonroot

    sut:
        build:
            context: .
            dockerfile: Dockerfile.test
        links:
            - web

